name: BT Space Race
favicon: null
layout_spectrum: 0
typography_spectrum: 0.00485
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#06050b'
    - '#9ad2ad'
    - '#5c836e'
    - '#e785f7'
  brandStrength: 1
  lightness: 0.6741193064954132
  saturation: 0.5424012150615454
  rhythmicContrast: 0.4576138292904943
purpose: []
